//autogenerated by msp430-gen.py
#ifndef _PINS_H
#define _PINS_H

#define CLOCK_PINS        (BIT2|BIT5|BIT4)
#define CLOCK_DIR         P1DIR
#define CLOCK_SEL0        P1SEL0
#define CLOCK_SEL1        P1SEL1

//pins : P3.5 P3.6  
#define UART_TX_PIN_NUM   5
#define UART_RX_PIN_NUM   6
#define UART_PORT         3

#define UART_TX_PIN       (1<<(UART_TX_PIN_NUM))
#define UART_RX_PIN       (1<<(UART_RX_PIN_NUM))
#define UART_PINS         (UART_RX_PIN|UART_TX_PIN)

//define sensor I2C pins
#define SEN_PORT          4
#define SEN_SDA_PIN_NUM   0
#define SEN_SCL_PIN_NUM   1

//define magnetometer Set/Reset pin
#define MAG_SR_PIN        BIT0
#define MAG_SR_DIR        P6DIR
#define MAG_SR_OUT        P6OUT
#define MAG_SR_SEL0       P6SEL0
#define MAG_SR_SEL1       P6SEL1


//define serial pins
#define BUS_PIN_SDA       BIT1
#define BUS_PIN_SCL       BIT0

#define BUS_PINS_I2C      (BUS_PIN_SDA|BUS_PIN_SCL)

#define BUS_PIN_SCK       BIT2
#define BUS_PIN_SOMI      BIT3
#define BUS_PIN_SIMO      BIT4
  
#define BUS_PINS_SPI      (BUS_PIN_SOMI|BUS_PIN_SIMO|BUS_PIN_SCK)  

#define BUS_PINS_SER      (BUS_PINS_SPI|BUS_PINS_I2C)

#endif
